---
name: build

on:
  push:
    branches:
      - "*"
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/sitepilot/runtime:latest .

      - name: Publish Docker image
        run: |
          DOCKER_TAG=${GITHUB_REF##*/};
          DOCKER_TAG=${DOCKER_TAG#"v"};

          docker tag ghcr.io/sitepilot/runtime:latest ghcr.io/sitepilot/runtime:$DOCKER_TAG

          docker push ghcr.io/sitepilot/runtime:latest
          docker push ghcr.io/sitepilot/runtime:$DOCKER_TAG
        if: github.event.release
